/**
 * 地标中文名：优先用中文 Wiki / eftarkov 已有叫法
 * https://www.eftarkov.com/news/web_176.html
 * https://api.eftarkov.com/map/customs/
 * https://escapefromtarkov.fandom.com/zh/wiki/海关
 */
export const PLACE_ZH: Record<string, string> = {
  "Abandon Factory": "废弃工厂",
  ADIK: "ADIK",
  Admin: "行政楼",
  "Administrative Office": "行政办公室",
  Arena: "竞技场",
  "ASAP Winery": "酒庄",
  Avokado: "牛油果",
  Barracks: "营房",
  Beluga: "白鲸",
  "Big Red": "大红", // 海关大红楼，中文圈通用叫法
  "Bilbo Coffee": "比尔博咖啡",
  Bizarro: "奇趣",
  "Black Bishop": "黑象",
  "Black Knight": "黑马",
  "Black Pawn": "黑兵",
  "Blue Containers": "蓝色集装箱",
  Boathouses: "船屋",
  "Boiler Room": "锅炉房",
  Boilers: "锅炉",
  "Book Store": "书店",
  "Boots 4 Life": "靴子店",
  "Breach Room": "突破室",
  Brutal: "Brutal",
  Bunker: "地堡",
  "Burger House": "汉堡屋",
  "Burger Spot": "汉堡店",
  "Bus Station": "公交站",
  "Bus Stop": "公交站",
  Cabins: "木屋",
  Cafeteria: "食堂",
  "Capital Insight": "资本洞察",
  "Cardinal Apartments": "红衣主教公寓",
  "Cardinal Bank": "红衣主教银行",
  "Cargo Containers": "货柜",
  Checkpoint: "检查站",
  "Chekannaya St.": "切坎纳亚街",
  Cinema: "电影院",
  "Coffee Joy": "欢乐咖啡",
  Concordia: "康科迪亚",
  "Conference Room": "会议室",
  Connector: "连接廊",
  Construction: "工地",
  "Control Room": "控制室",
  Convenience: "便利店",
  Convoy: "车队",
  "Corner Restaurant": "转角餐厅",
  "Corridor To Building #2": "通往2号楼走廊",
  Cottages: "别墅",
  Crackhouse: "裂纹屋",
  Crane: "吊车",
  "Crash Site": "坠机点",
  "Cultist Village": "邪教村",
  "Dead Tree": "枯树",
  Depot: "仓库站",
  Diner: "餐厅",
  "Dino Clothes": "恐龙服装",
  Dom: "Dom",
  Dome: "圆顶",
  Dorms: "宿舍", // Wiki：宿舍楼
  "Drug Lab": "制毒实验室",
  "E1 Bunkers": "E1 地堡",
  "E2 Bunkers": "E2 地堡",
  "East Halls": "东厅",
  "East Wing": "东翼",
  Eastland: "东区",
  "Elemental Global": "元素全球",
  EMERCOM: "紧急情况部",
  Empire: "帝国",
  "Family Market": "家庭超市",
  "Fashion Store": "时装店",
  "Father & Sons": "父子店",
  FCK: "FCK",
  Figaro: "费加罗",
  Forklifts: "叉车",
  Fortress: "要塞",
  "Four Camp": "四方营地",
  Fusion: "Fusion",
  "GAGRIN Hotel": "加加林酒店",
  Garage: "车库",
  "Garage A": "车库 A",
  "Garage B": "车库 B",
  "Garage C": "车库 C",
  "Garage D": "车库 D",
  "Gas Station": "加油站",
  Generic: "通用",
  German: "德国车",
  "Glass Hall": "玻璃厅",
  "Go Kart": "卡丁车",
  Goshan: "Goshan",
  "Grand Chalet": "大木屋",
  "Gunner Nest": "机枪巢",
  Gym: "健身房",
  "Heli Crash": "直升机坠毁",
  "Highway Construction": "高速工地",
  Hillside: "山坡",
  Hive: "蜂巢",
  Hole: "破洞",
  IDEA: "IDEA",
  "Idea Tower": "IDEA 塔",
  "Infirmary Lvl 1": "医务室 1层",
  "Infirmary Lvl 2": "医务室 2层",
  Intourist: "因图里斯特",
  Island: "小岛",
  "Jacob & Jacob": "雅各布",
  "Jaeger's Camp": "耶格营地",
  "Junk Bridge": "废品桥",
  "K Buildings": "K 楼",
  K1: "K1",
  K2: "K2",
  K3: "K3",
  K4: "K4",
  K5: "K5",
  K6: "K6",
  "Kamchatskaya St.": "堪察加街",
  Kiba: "Kiba",
  "Kilmov Shopping Mall": "基尔莫夫商场",
  "Kilmov St.": "基尔莫夫街",
  Kostin: "科斯京",
  "Lecture Hall": "报告厅",
  "LERM Expo": "LERM 展会",
  Lexos: "Lexos",
  "Lightkeeper Island": "灯塔岛",
  "Locked Office": "上锁办公室",
  "Locker Rooms": "更衣室",
  Lumber: "木材场",
  "M Showroom": "M 展厅",
  "Main Bridge": "主桥",
  "Main Office": "主办公",
  "Main Working Area": "主作业区",
  "Malevecha St.": "马列韦恰街",
  Mantis: "螳螂",
  "Marked Hotel": "标记酒店",
  McDaniels: "麦丹尼",
  Mechanic: "技工",
  "Med Tent": "医疗帐篷",
  "Men's Locker Room": "男更衣室",
  "Military Camp": "军营",
  "Military Checkpoint": "军事基地检查站", // eftarkov 撤离点/钥匙名
  Mode7: "Mode7",
  Nakatani: "中谷",
  "Negotiation Room": "谈判室",
  "New Gas": "新加油站",
  "Nikitskaya St.": "尼基茨卡亚街",
  "Nizhnyaya St.": "下街",
  Nortex: "Nortex",
  "North Stairs": "北楼梯",
  Oasis: "绿洲",
  Office: "办公室",
  "Office Building": "办公楼",
  "Offices #1": "办公室 1",
  "Offices #2": "办公室 2",
  "Old Construction": "旧工地",
  "Old Gas": "老加油站", // eftarkov / Wiki
  "Old Sawmill": "旧锯木厂",
  OLI: "OLI",
  "Oli Tower": "OLI 塔",
  Papillon: "蝴蝶",
  Parking: "停车场",
  "Pharmacy 1": "药店 1",
  "Pharmacy 2": "药店 2",
  "Pharmacy 3": "药店 3",
  "Philly Cute": "Philly Cute",
  Pier: "码头",
  "Pikes Peak Resort": "派克斯峰度假村",
  "Pinewood Hotel": "松木酒店",
  Pipes: "管道",
  Pit: "深坑",
  "Plant 1": "车间 1",
  "Plant 2": "车间 2",
  "Plant 3": "车间 3",
  Platform: "月台",
  Ponds: "池塘",
  "Post Office": "邮局",
  "Power Station": "发电站",
  "Powerline Tower": "高压塔",
  "Prestigio Cafe": "声望咖啡",
  "Pretty Lights": "彩灯",
  "Primorskij 49": "滨海 49",
  "Primorsky Ave.": "滨海大街",
  "Pumping Station": "泵站",
  "Radio Tower": "无线电塔",
  Rafters: "椽木",
  Ramps: "坡道",
  Rasmussen: "拉斯穆森",
  "Razvedchikov St.": "侦察兵街",
  Reception: "前台",
  "Recreation Area": "休闲区",
  "Red Brick": "红砖",
  "Repair Shop": "修理店",
  Resort: "度假村",
  Revis: "Revis",
  SARA: "SARA",
  Sawmill: "锯木厂",
  "Scav Bunker": "Scav 地堡",
  "Scav Camp": "Scav 营地",
  "Scav Farm": "Scav 农场",
  "Scav Island": "Scav 岛",
  "Scav Town": "Scav 镇",
  School: "学校",
  "Science Office": "科学办公室",
  "Security #1": "安保 1",
  "Security #2": "安保 2",
  "Security Barracks": "安保营房",
  "Security Office": "安保室",
  "Server Room": "服务器室",
  Servers: "服务器",
  Shack: "棚屋",
  Shestyorochka: "六点超市",
  Shiccos: "Shiccos",
  "Shipping Yard": "船运场",
  Silos: "筒仓",
  Sinks: "水槽",
  Skeleton: "烂尾楼", // Wiki：烂尾楼
  "Sky Bridge": "天桥",
  Skyside: "天侧",
  "Sniper Hill": "狙击山",
  "Sniper Ridge": "狙击岭",
  "Sniper Rock": "狙击岩",
  "South Hotel": "南酒店",
  "South Stairs": "南楼梯",
  "Sparja Express": "Sparja 便利",
  "Sparja Grocery": "Sparja 杂货",
  Spiel: "Spiel",
  Sports: "体育",
  "Sterile Laboratory": "无菌实验室",
  Storage: "仓库区",
  "Streamer House": "主播屋",
  "Sushi Huyushi": "寿司",
  Swamp: "沼泽",
  "Tank Bridge": "坦克桥",
  Tarbank: "塔银行",
  Tarducks: "塔巴克",
  Tarkovstar: "塔科夫之星",
  Tarmac: "停机坪",
  TECHLIGHT: "TECHLIGHT",
  Telespot: "Telespot",
  "Tennis Court": "网球场",
  "Teppakot / Koener": "Teppakot / Koener",
  TerraGroup: "TerraGroup",
  "Test Room": "测试室",
  Texho: "Texho",
  "The National": "国家酒店",
  "Top Brand": "顶级品牌",
  "Trailer Park": "拖车停车场", // eftarkov 撤离点名
  "Train Station": "火车站",
  "Train Yard": "火车场",
  TRend: "TRend",
  TTS: "TTS",
  "Underground Stash": "地下藏匿",
  Underway: "地下通道",
  "Urban Clothes": "都市服装",
  "USEC Camp": "USEC 营地",
  "Verhnyaya St.": "上街",
  "Vestibules #1": "前厅 1",
  "Vestibules #2": "前厅 2",
  "Vet Clinic": "兽医诊所",
  Viking: "维京",
  Village: "村庄",
  Voyage: "Voyage",
  "Wall Break": "破墙",
  Warehouse: "仓库",
  "Warehouse 17": "17号仓库",
  "Warehouse 3": "3号仓库",
  "Warehouse 4": "4号仓库",
  "Warehouse 7": "7号仓库",
  "Warehouse Gate": "仓库大门",
  "Warehouse Tunnels": "仓库隧道",
  "Water Treatment": "水处理",
  "Weather Station": "气象站",
  "West Wing": "西翼",
  "White Bishop": "白象",
  "White King": "白王",
  "White Knight": "白马",
  "White Pawn": "白兵",
  "White Queen": "白后",
  "White Rook": "白车",
  "Women's Locker Room": "女更衣室",
  "Wood Room": "木屋房间",
  Yushka: "Yushka",
  "Zmejskij Alley": "蛇巷",
  "д - Warehouse Bunkers": "仓库地堡",
};

export function placeName(text: string): string {
  return PLACE_ZH[text] ?? text;
}
